image:
 name: hashicorp/terraform:latest
 entrypoint: [""]

variables:
 AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
 AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}

before_script:
 - apk add --no-cache nodejs npm
 - apk add aws-cli
 - apk add bash
 - apk add npm
 - export PATH="/usr/local/bin:$PATH"

stages:
  - validate
  - plan
  - apply

validate:
 stage: validate
 before_script:
   - apk update && apk add --no-cache nodejs npm
   - npm install -g npm@latest
   - npm ci
 artifacts:
   paths:
    - node_modules/
    - dist/
    - terraform.tfstate
    - .terraform.lock.hcl
 script:
  - terraform init -backend=false
  - terraform validate
  - npm run build

plan:
 stage: plan
 script:
  - terraform init 
  - terraform plan -out terraform.tfplan
 artifacts:
  paths:
   - dist/
   - node_modules/
   - terraform.tfstate
   - .terraform.lock.hcl
   - terraform.tfplan
 dependencies:
  - validate

apply:
  stage: apply
  script:
    - terraform apply -auto-approve terraform.tfplan || npm run build
    - npm run build
    - terraform apply -auto-approve
  artifacts:
    paths:
    - dist/
    - terraform.tfstate
    - .terraform.lock.hcl
  only:
    - main
