image:
 name: hashicorp/terraform:latest
 entrypoint: [""]

variables:
 AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
 AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}

before_script:
 - apk add --no-cache nodejs npm
 - apk add aws-cli
 - apk add bash
 - apk add npm
 - export PATH="/usr/local/bin:$PATH"

stages:
  - validate
  - plan
  - apply

validate:
 stage: validate
 artifacts:
   paths:
    - terraform.tfstate
    - .terraform.lock.hcl
 script:
  - terraform init -backend=false
  - terraform validate

plan:
 stage: plan
 before_script:
   - apk update && apk add --no-cache nodejs npm
   - npm install -g npm@latest
   - npm ci
 script:
  - terraform init 
  - terraform plan -out terraform.tfplan
 artifacts:
  paths:
   - dist/
   - node_modules/
   - terraform.tfstate
   - .terraform.lock.hcl
   - terraform.tfplan
   - npm run build
 dependencies:
  - validate

apply:
  stage: apply
  script:
    - terraform init 
    - terraform apply -auto-approve terraform.tfplan || terraform apply -auto-approve 
    - npm run build
    - terraform apply -auto-approve
  artifacts:
    paths:
    - dist/
    - node_modules/
    - terraform.tfstate
    - .terraform.lock.hcl
  only:
    - main
