image: node:18

stages:
  - build
  - deploy

before_script:
  - npm install -g npm@latest

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - build/
    expire_in: 1 week

deploy:
  image: hashicorp/terraform:latest
  stage: deploy
  script:
    - terraform init
    - terraform apply -auto-approve
  environment:
    name: production
  dependencies:
    - build
  before_script:
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
