include:
  - template: Terraform/Base.gitlab-ci.yml  # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Terraform/Base.gitlab-ci.yml
  - template: Jobs/SAST-IaC.gitlab-ci.yml   # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Jobs/SAST-IaC.gitlab-ci.yml

variables:
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}

kics-iac-sast:
  variables:
    SAST_ANALYZER_IMAGE_TAG: "4.1.11"

before_script:
 - apk update --repository=http://dl-cdn.alpinelinux.org/alpine/v3.13/main
 - apk add aws-cli
 - apk add bash
 - apk add npm
 - export PATH="/usr/local/bin:$PATH"

stages:
  - validate
  - test
  - build
  - deploy
  # - destroy
  - cleanup

fmt:
  extends: .terraform:fmt
  needs: []

validate:
  extends: .terraform:validate
  needs: []

cache:
  paths:
    - node_modules/

build_and_deploy:
  stage: build
  image: hashicorp/terraform:1.0.11
  environment:
    name: $TF_STATE_NAME
    action: prepare
  before_script:
    - apk update && apk add --no-cache nodejs npm
    - npm install -g npm@latest
    - npm ci
  script:
    - npm run build
    - terraform init
    - terraform plan
    - terraform apply -auto-approve
  artifacts:
    paths:
      - dist/
  only:
    - main

deploy:
  stage: deploy
  dependencies:
    - build_and_deploy
  environment:
    name: $TF_STATE_NAME
    action: start
  script:
    - terraform init
    - terraform plan
    - terraform apply -auto-approve
  before_script:
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
  when: on_success

# destroy:
#   extends: .terraform:destroy
#   environment:
#     name: $TF_STATE_NAME
#     action: stop
#   script:
#     - terraform init && terraform destroy -auto-approve
#   before_script:
#     - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
#     - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
#   when: manual
